### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by idkjs** [javamonn/trashed#3]
Greetings @javamonn. I am an avid code reader and your work here is unique in reasonml repos on github in that it demonstrates some outside the box uses and patterns. Your build code/scripts, for example, is interesting. I just wanted to say thank you for sharing it. I also wanted to ask you, if you find your able, to maybe write some "french" style code [comments](https://opensource.janestreet.com/standards/). I say french because it seems like they comment the hell out of everything and its great for learning. Anyway, if you can, great. If not, I will still be spying. If you are open to getting questions about why you did something, please let me know. I don't wan't to blow up your repo with questions, if not.

Peace and love to you.

**Comment by javamonn** [comment]
Hi @idkjs, thanks for the note! 

This repo follows an overall philosophy I encountered while at Artsy, where ["Open Source By Default"](https://artsy.github.io/open-source/) encourages making code accessible to the outside world, but not necessarily accepting or encouraging outside contributions. 

Because of this, to your point, the repo is definitely in a state where it's lacking in documentation, as I'm currently the only one actively contributing code to it. That being said there's likely a set of documentation towards the overall structure and components that could be valuable.

In the meantime, I'm totally open to answering questions about anything! Feel free to continue to open issues like this one.

**Comment by idkjs** [comment]
Thank you, sir. You willingness to teach is most def appreciated. Thanks for the link. Will read it shortly.
